- alias: Startup Theme
  id: '20180524211900'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  action:
  - service_template: "{% if states.sun.sun.state == \"above_horizon\" %}\n  shell_command.dark_to_clear_wp\n\
      {% else %}\n  shell_command.clear_to_dark_wp\n{% endif %}\n"
  - service_template: frontend.set_theme
    data_template:
      name: "{% if states.sun.sun.state == \"above_horizon\" %}\n  clear\n{% else\
        \ %}\n  dark_clear\n{% endif %}\n"
  - service: script.lovelace_reload
  
- alias: SSL expiry notification
  id: '1500779870955'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry
    below: 21
  action:
    service: !secret notify_ios
    data_template:
      message: Warning - SSL certificate expires in {{ states.sensor.ssl_certificate_expiry.state
        }} days and has not been automatically renewed.

- alias: Update notifications
  id: '49494'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: !secret notify_ios
    data_template:
      message: Home Assistant {{ states.updater.updater.state }} is now available.

- alias: Disk Use Alarm
  id: '7592974'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use
    above: 90
  action:
    service: !secret notify_ios
    data_template:
      message: 'Your harddrive is running out of space: /dev/root: {{ states.sensor.disk_use_percent.state
        }}%'

- alias: Lights and TV off
  id: '756390032'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == (states.input_datetime.time_turnoff_devices.attributes.timestamp
      | int | timestamp_custom("%H:%M", False)) }}'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
      - media_player.braviatv_1
      - media_player.playstation_4
      - light.schlafzimmer
      - light.badezimmer
      - light.kuche
      #- light.vorzimmer
      - light.toilette
      - light.wohnzimmer

- alias: Sonoff-Tasmota update availability
  id: '111999111'
  trigger:
    platform: time
    at: 09:15:00
  condition:
    condition: template
    value_template: '{{ states.sensor.sonoff_maddox_version.state | replace("v", "")
      != states.sensor.sonoff_3028_version.state[:5] }}'
  action:
  - service: !secret notify_ios
    data_template:
      message: 'Sonoff-Tasmota version {{ states.sensor.sonoff_maddox_version.state
        | replace("v", "") }} is available. Do you wish to upgrade? Changelog: https://is.gd/tasmota'
      data:
        push:
          category: sonoffupdate
- alias: Update Sonoff-Tasmota
  id: '999111999'
  trigger:
    platform: event
    event_type: mobile_app.notification_action_fired
    event_data:
      actionName: UPDATE_SONOFF
  action:
  - service: script.1515151540311

- alias: get sonoff 3028 version
  id: '1500581870914'
  trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: 09:00:00
  action:
  - service: mqtt.publish
    data:
      topic: wemosd1_1/cmnd/Status
      payload: '0'
  - service: mqtt.publish
    data:
      topic: sonoff_3082/cmnd/Status
      payload: '0'
  - service: mqtt.publish
    data:
      topic: sonoff_3463/cmnd/Status
      payload: '0'

- alias: left home device1
  id: '1515583360531'
  trigger:
  - entity_id: !secret person_1
    for:
      minutes: 5
    from: home
    platform: state
    to: not_home
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
      - media_player.braviatv_1
      - media_player.playstation_4
      - light.schlafzimmer
      - light.badezimmer
      - light.kuche
      - light.vorzimmer
      - light.toilette
      - light.wohnzimmer
      - input_boolean.loop_livingcolors_1
      - input_boolean.loop_livingcolors_2

- alias: Log Level
  id: '1500589870955'
  trigger:
    platform: state
    entity_id: input_select.log_level
  condition:
    condition: template
    value_template: '{{ states.input_select.log_level.state != "none" }}'
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: '{{ trigger.to_state.state }}'

- alias: WakeUp Light Bedroom
  id: '1500581870955'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state
      }}'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: state
      entity_id: !secret person_1
      state: home
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.wakeup_weekends
        state: 'on'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: script.wakeup_schlafzimmer

- alias: Hue Scene Activation
  id: '1500589870955'
  trigger:
    platform: state
    entity_id: input_select.hue_scenes
  condition:
    condition: template
    value_template: '{{ states.input_select.hue_scenes.state != "none" }}'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Zimmer
      scene_name: '{{ trigger.to_state.state }}'
  - delay:
      seconds: 3
  - service: input_select.select_option
    data:
      entity_id: input_select.hue_scenes
      option: none

- alias: Random light
  id: '33223'
  trigger:
    platform: time_pattern
    minutes: /2
    seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_livingcolors_1
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.deckenspots
    data:
      entity_id: light.deckenspots
      effect: random
      transition: 5
      brightness: 255

- id: '1519076898412'
  alias: Gaming PS4
  trigger:
  - entity_id: media_player.playstation_4
    platform: state
    to: playing
  condition:
  - after: '19:00:00'
    condition: time
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: !secret person_1
    state: home
  action:
  - data:
      group_name: Deckenleuchte
      scene_name: Arctic aurora
    service: hue.hue_activate_scene

- id: '1519077187087'
  alias: Stop playing PS4
  trigger:
  - entity_id: media_player.playstation_4
    from: playing
    platform: state
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - after: '21:00:00'
    condition: time
  - condition: state
    entity_id: !secret person_1
    state: home
  action:
  - data:
      group_name: Deckenleuchte
      scene_name: Nightlight
    service: hue.hue_activate_scene

- id: '1519077406569'
  alias: Ready for bed
  trigger:
  - at: '21:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: !secret person_1
    state: home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      group_name: Wohnzimmer
      scene_name: Nightlight
    service: hue.hue_activate_scene

- alias: Random light - Stehlampe
  id: '20180513163100'
  trigger:
    platform: time_pattern
    minutes: /2
    seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_livingcolors_2
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.stehlampe
      effect: random
      transition: 5
      brightness: 132

- id: '1553547958805'
  alias: Turn off magic mirror
  trigger:
  - entity_id: sensor.is_home
    for:
      minutes: 15
    from: 'true'
    platform: state
    to: 'false'
  action:
  - data:
      entity_id: switch.magic_mirror
    service: switch.turn_off

- id: '1553548399232'
  alias: Turn on magic mirror
  trigger:
  - entity_id: !secret person_1
    platform: state
    to: home
  action:
  - data:
      entity_id: switch.magic_mirror
    service: switch.turn_on

- id: '1555301143838'
  alias: turn off loop-effect Stehlampe
  trigger:
  - entity_id: light.stehlampe
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: input_boolean.loop_livingcolors_2
    service: input_boolean.turn_off

- id: '1555301210835'
  alias: turn off loop-effekt Deckenspots
  trigger:
  - entity_id: light.deckenspots
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: input_boolean.loop_livingcolors_1
    service: input_boolean.turn_off

- id: '1555971390000'
  alias: robovac auto turn on
  trigger:
  - platform: time_pattern
    minutes: '/30'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: counter.vacuum_counter
        below: 2
      - condition: state
        entity_id: sensor.is_home
        state: 'false'
        for:
          minutes: 20
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.robovac_battery
                state: '100'
              - condition: numeric_state
                entity_id: counter.vacuum_counter
                below: 2
              - condition: time
                after: '07:00:00'
                before: '15:00:00'
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sensor.robovac_battery
                above: 85
              - condition: state
                entity_id: counter.vacuum_counter
                state: '1'
              - condition: time
                after: '13:00:00'
                before: '15:30:00'
  action:
  - service: vacuum.turn_on
    data:
      entity_id: vacuum.robovac
  
- id: '15559713900111'
  alias: robovac clean counter
  trigger:
  - platform: template
    value_template: "{{ is_state_attr('vacuum.robovac', 'status', 'cleaning') }}"
  action:
  - service: counter.increment
    data:
      entity_id: counter.vacuum_counter

- id: '15559754790000'
  alias: robovac clean notification
  trigger:
  - platform: time_pattern
    hours: '/2'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret person_1
        state: 'home'
        for:
          minutes: 20
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
      - condition: numeric_state
        entity_id: counter.vacuum_counter
        above: 0
  action:
  - service: !secret notify_ios
    data_template:
      message: 'Schurli ist zu entleeren. Anzahl der Saugvorg√§nge: {{ states.counter.vacuum_counter.state }}'
      data:
        push:
          category: emptyrobovac

- alias: robovac cleaned
  id: '15559754790001'
  trigger:
    platform: event
    event_type: mobile_app.notification_action_fired
    event_data:
      actionName: EMPTY_ROBOVAC_NOW
  condition:
    condition: state
    entity_id: !secret person_1
    state: 'home'
  action:
  - service: counter.reset
    data:
      entity_id: counter.vacuum_counter