---

title: Home

x-vacuum-buttons: &vacuum-buttons
  color: auto
  entity: vacuum.roborock
  size: 25%

# background: center / cover repeat-y url("/local/background/dark-wp.jpg") fixed

excluded_entities: !include /config/lovelace/excluded-entities.yaml

views: !include_dir_merge_list lovelace/views/
