---
# media player customization

media_player.sony_bravia_tv:
  friendly_name: Sony Bravia TV
  icon: mdi:television
  source_list:
    - 'ORF eins HD'
    - 'ORF 2 Wien HD'
    - 'ATV HD'
    - 'PULS 4 HD'
    - 'Das Erste HD'
    - 'ZDF HD'
    - 'ORF III HD'
    - 'ProSieben HD'
    - 'RTL HD'
    - 'SAT.1 HD'
    - 'RTLZWEI HD'
    - 'Kabel Eins HD'
    - 'VOX HD'
    - 'ATV2 HD'
    - 'Kabel Eins Doku'
    - 'arte HD'
    - 'Nitro HD'
    - 'N24 doku'
    - 'n-tv HD'
    - 'Comedy Central HD'
    - 'PULS24 HD'
    - 'ZDF neo HD'
    - 'Phoenix HD'
    - 'ZDF info HD'
    - 'One HD'
    - 'ARD alpha HD'
    - 'ORF Sport+ HD'
    - 'Sky Sport News HD'
    - 'Sport 1 HD'
    - 'Eurosport 1 HD'
    - 'Sky 1 HD'
    - 'Sky Sport Austria 1 HD'
    - 'Sky Sport Austria 2 HD'
    - 'Sky Sport HD 1'
    - 'Sky Sport HD 2'
    - 'Sky Bundesliga HD 1'
    - 'Sky Bundesliga HD 2'
    - 'Netflix'
    - 'YouTube'
    - 'Prime Video'
    - 'maxdome'
    - 'Kodi'
    - 'ORF TVthek'
    - 'ZDFmediathek'
    - 'VLC'
    - 'HDMI 1'
    - 'PlayStation 4'
    - 'HDMI 3/ARC'
    - 'HDMI 4'
