---
# Plants view

- icon: mdi:sprout
  title: plants
  visible: false
  path: plants
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # Plants
            ## My poor plants. May the light be with them.
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                  height: 70px !important;
                }
              ha-markdown:
                $: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        # - type: horizontal-stack # kentia
        #   cards:
        #     - type: 'custom:button-card'
        #       show_icon: false
        #       show_name: false
        #       style: |
        #         ha-card {
        #         --ha-card-background: 'rgba(11, 11, 11, 0.00)';
        #         box-shadow: 2px 2px rgba(0,0,0,0.0);
        #         }
        #       styles:
        #         card:
        #           - width: 5px
        #           - height: 60px
        #     - type: plant-status
        #       entity: plant.howea_forsteriana
        #       style: |
        #         ha-card {
        #           background-color: var(--primary-background-color);
        #           border-radius: 15px;
        #           box-shadow: var(--softui-standard-boxshadow);
        #         }
        #     - type: 'custom:button-card'
        #       show_icon: false
        #       show_name: false
        #       style: |
        #         ha-card {
        #         --ha-card-background: 'rgba(11, 11, 11, 0.00)';
        #         box-shadow: 2px 2px rgba(0,0,0,0.0);
        #         }
        #       styles:
        #         card:
        #           - width: 5px
        #           - height: 60px
        # - type: 'custom:button-card'
        #   show_icon: false
        #   show_name: false
        #   style: |
        #     ha-card {
        #       --ha-card-background: 'rgba(11, 11, 11, 0.00)';
        #       box-shadow: 2px 2px rgba(0,0,0,0.0);
        #     }
        #   styles:
        #     card:
        #       - width: 5px
        #       - height: 10px
        - type: horizontal-stack  # kentia
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
            - type: plant-status
              entity: plant.howea_forsteriana
              card_mod:
                style: |
                  ha-card {
                    background-color: var(--primary-background-color);
                    border-radius: 15px;
                    box-shadow: var(--softui-standard-boxshadow);
                  }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
        - type: 'custom:button-card'
          show_icon: false
          show_name: false
          styles:
            card:
              - width: 5px
              - height: 10px
              - box-shadow: '2px 2px rgba(0,0,0,0.0)'
              - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
        - type: horizontal-stack  # yucca
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
            - type: plant-status
              entity: plant.yucca_aloifolia
              card_mod:
                style: |
                  ha-card {
                    background-color: var(--primary-background-color);
                    border-radius: 15px;
                    box-shadow: var(--softui-standard-boxshadow);
                  }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
        - type: 'custom:button-card'
          show_icon: false
          show_name: false
          styles:
            card:
              - width: 5px
              - height: 10px
              - box-shadow: '2px 2px rgba(0,0,0,0.0)'
              - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
